# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Donut < Formula
  desc "Tiny dotfiles management tool written in Go."
  homepage "https://github.com/croixxant/donut"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "http://github.com/croixxant/donut/releases/v0.0.1/donut_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "16ee99c02ed95b2df707c910eb59a6f302f340c86df6c51285a2c4a1e5471da3"

      def install
        bin.install "donut"
      end
    end
    if Hardware::CPU.arm?
      url "http://github.com/croixxant/donut/releases/v0.0.1/donut_0.0.1_Darwin_arm64.tar.gz"
      sha256 "23920b7c8158a636503732571c7233eb21d50aca581b0f6bb06d9b709b089e58"

      def install
        bin.install "donut"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://github.com/croixxant/donut/releases/v0.0.1/donut_0.0.1_Linux_arm64.tar.gz"
      sha256 "37035ee3eb52baf0bf2ce55b1c5e0bce08ac998270a4c6e32c5ecabfcd63f7e9"

      def install
        bin.install "donut"
      end
    end
    if Hardware::CPU.intel?
      url "http://github.com/croixxant/donut/releases/v0.0.1/donut_0.0.1_Linux_x86_64.tar.gz"
      sha256 "4d2056b159c480f760e73a3c1d85f767e8f1fea07849b77dadf018344feb7129"

      def install
        bin.install "donut"
      end
    end
  end

  test do
    system "#{bin}/donut --version"
  end
end
