# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Donut < Formula
  desc "Tiny dotfiles management tool written in Go."
  homepage "https://github.com/croixxant/donut"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/croixxant/donut/releases/download/v0.0.1/donut_0.0.1_Darwin_arm64.tar.gz"
      sha256 "ee7b3609196de0e678caacd4960ab26aa1a802f1b543b559f153e948ce4dc58d"

      def install
        bin.install "donut"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/croixxant/donut/releases/download/v0.0.1/donut_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "eec9ff7fd89ba614ded4f352439b1ad00a257fea3311a21802ad2c7f37550594"

      def install
        bin.install "donut"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/croixxant/donut/releases/download/v0.0.1/donut_0.0.1_Linux_x86_64.tar.gz"
      sha256 "1de1ff2775e1202bd188327f80a4cad90a30462550ee06925d26fee5ab4a99c7"

      def install
        bin.install "donut"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/croixxant/donut/releases/download/v0.0.1/donut_0.0.1_Linux_arm64.tar.gz"
      sha256 "cc64845bd461c8af5eafa9acd6bb961adea41c0a66187dc4ded12e1a8526207b"

      def install
        bin.install "donut"
      end
    end
  end

  test do
    system "#{bin}/donut --version"
  end
end
