# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Donut < Formula
  desc "Tiny dotfiles management tool written in Go."
  homepage "https://github.com/croixxant/donut"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/croixxant/donut/releases/download/v0.0.2/donut_0.0.2_Darwin_x86_64.tar.gz"
      sha256 "e7cb3e27bb0ca6d85fff5062e504cb4e667d95ebf962647a107de3c083d62f1c"

      def install
        bin.install "donut"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/croixxant/donut/releases/download/v0.0.2/donut_0.0.2_Darwin_arm64.tar.gz"
      sha256 "b57f44772f1fbcf52ad61dd3ee447d6912e6476b65de72ae910ceee1ac707ca3"

      def install
        bin.install "donut"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/croixxant/donut/releases/download/v0.0.2/donut_0.0.2_Linux_arm64.tar.gz"
      sha256 "9c19940afa71e5ff6c8d1e81137b34f15fae5e5f0900a6019a9ddac415c5808a"

      def install
        bin.install "donut"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/croixxant/donut/releases/download/v0.0.2/donut_0.0.2_Linux_x86_64.tar.gz"
      sha256 "cda47d8a220a853e1fa7dff12a7cd9251a6b46bab2acedec7a36d03e1ebcf95d"

      def install
        bin.install "donut"
      end
    end
  end

  test do
    system "#{bin}/donut --version"
  end
end
